
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.awt.event.*;
import javax.swing.ImageIcon;
import java.util.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newuser.java
 *
 * Created on Jan 4, 2015, 12:41:33 PM
 */

/**
 *
 * @author mukesh
 */
public class newuser extends javax.swing.JFrame {

    /** Creates new form newuser */
    public newuser() {
        initComponents();
         Timer t2=new Timer(300,new ActionListener(){
            public void actionPerformed(ActionEvent e){
                int i=Integer.parseInt(ctr.getText());
                int j = i%27;
                i++;
                ctr.setText(""+i);
                ctr.setVisible(false);
                switch(j){
                    case 0:Img.setIcon(new ImageIcon("E:\\pics\\1.PNG"));
                        break;
                    case 1:Img.setIcon(new ImageIcon("E:\\pics\\2.PNG"));
                        break;
                    case 3:Img.setIcon(new ImageIcon("E:\\pics\\3.PNG"));
                        break;
                    case 4:Img.setIcon(new ImageIcon("E:\\pics\\4.PNG"));
                        break;
                    case 5:Img.setIcon(new ImageIcon("E:\\pics\\5.PNG"));
                        break;
                    case 6:Img.setIcon(new ImageIcon("E:\\pics\\6.PNG"));
                        break;
                    case 7:Img.setIcon(new ImageIcon("E:\\pics\\7.jpg"));
                        break;
                    case 8:Img.setIcon(new ImageIcon("E:\\pics\\8.jpg"));
                        break;
                    case 9:Img.setIcon(new ImageIcon("E:\\pics\\9.jpg"));
                        break;
                    case 10:Img.setIcon(new ImageIcon("E:\\pics\\10.jpg"));
                        break;
                    case 11:Img.setIcon(new ImageIcon("E:\\pics\\11.jpg"));
                        break;
                    case 12:Img.setIcon(new ImageIcon("E:\\pics\\12.jpg"));
                        break;
                    case 13:Img.setIcon(new ImageIcon("E:\\pics\\13.jpg"));
                        break;
                    case 14:Img.setIcon(new ImageIcon("E:\\pics\\14.jpg"));
                        break;
                    case 15:Img.setIcon(new ImageIcon("E:\\pics\\15.jpg"));
                        break;
                    case 16:Img.setIcon(new ImageIcon("E:\\pics\\16.jpg"));
                        break;
                    case 17:Img.setIcon(new ImageIcon("E:\\pics\\17.jpg"));
                        break;
                    case 18:Img.setIcon(new ImageIcon("E:\\pics\\18.jpg"));
                        break;
                    case 19:Img.setIcon(new ImageIcon("E:\\pics\\19.jpg"));
                        break;
                    case 20:Img.setIcon(new ImageIcon("E:\\pics\\20.jpg"));
                        break;
                    case 21:Img.setIcon(new ImageIcon("E:\\pics\\21.jpg"));
                        break;
                    case 22:Img.setIcon(new ImageIcon("E:\\pics\\22.jpg"));
                        break;
                    case 23:Img.setIcon(new ImageIcon("E:\\pics\\23.jpg"));
                        break;
                    case 24:Img.setIcon(new ImageIcon("E:\\pics\\24.jpg"));
                    j=0;
                        break;


                }
            }
          });
          t2.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        tf6 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        tf7 = new javax.swing.JPasswordField();
        Img = new javax.swing.JLabel();
        ctr = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADDING NEW USER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 270, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 130, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        tf2.setEnabled(false);
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 130, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        tf3.setEnabled(false);
        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        getContentPane().add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 130, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date Of Birth");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        tf4.setEnabled(false);
        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4ActionPerformed(evt);
            }
        });
        getContentPane().add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 170, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date Of Joinning");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        tf5.setEnabled(false);
        tf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf5ActionPerformed(evt);
            }
        });
        getContentPane().add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 170, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirm Password");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro (6).png"))); // NOI18N
        btn1.setText("<html><font size=5><b>A</b>dd ");
        btn1.setEnabled(false);
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 120, 70));

        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro (6).jpg"))); // NOI18N
        jButton2.setText("<html><font size=5><b>B</b>ack ");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 120, 70));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 20, 30));

        lbl.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 240, 40));

        tf6.setEnabled(false);
        tf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf6ActionPerformed(evt);
            }
        });
        getContentPane().add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 170, -1));

        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro (5).png"))); // NOI18N
        jButton3.setText("<html><font size=5><b>R</b>eset ");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 130, 70));

        tf7.setEnabled(false);
        tf7.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tf7CaretUpdate(evt);
            }
        });
        tf7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf7ActionPerformed(evt);
            }
        });
        getContentPane().add(tf7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 170, -1));

        Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erudite-wallpaper-star-shine-vector-graphics-high-resolution-image-cool-wallpaper-star-shine-vector-graphics-wallpapers-hd-for-iphone-android-mobile-pc-download-walls-facebook-ipad.jpg"))); // NOI18N
        Img.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 6, true));
        getContentPane().add(Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 610, 390));

        ctr.setText("1");
        getContentPane().add(ctr, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 10, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:




{
           try{
String name=tf1.getText();
String password=new String(tf6.getPassword());
String date=tf5.getText();


               Class.forName("java.sql.Driver");
               Connection con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/school1", "root", "tiger");

               Statement stmt = (Statement) con.createStatement();

               String qry = "insert into userid values('"+name+"','"+date+"','"+password+"');";
          stmt.executeUpdate(qry);

           JOptionPane.showMessageDialog(null,"Detailed added");


stmt.close();
con.close();


               }











           catch(Exception e)
           {
              JOptionPane.showMessageDialog(null , "oops Error in Coonectivity");

           }
        }
        this.dispose();
           new login().setVisible(true);
    }//GEN-LAST:event_btn1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         Calendar c=Calendar.getInstance();
        tf5.setText(tf5.getText()+""+c.get(Calendar.YEAR)+"-"+""+c.get(Calendar.MONTH+1)+"-"+"" +c.get(Calendar.DATE));
tf4.setText("YYYY/MM/DD");
tf1.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

              tf2.setText("");
              tf3.setText("");
              tf4.setText("");
              tf5.setText("");
              tf6.setText("");
              tf7.setText("");
              tf1.setText("");
              lbl.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tf7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf7ActionPerformed

    private void tf7CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tf7CaretUpdate
        // TODO add your handling code here:
        String io = new String (tf6.getPassword());
        String lo = new String (tf7.getPassword());
        if(io.equals(lo)){


            lbl.setText("Password Confirmed");
            btn1.setEnabled(true);
        }
 else
     lbl.setText("Password Not Confirmed");
       
    }//GEN-LAST:event_tf7CaretUpdate

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
        tf2.setEnabled(true);
        tf2.requestFocus();
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        // TODO add your handling code here:
           tf4.setEnabled(true);
        tf4.requestFocus();

    }//GEN-LAST:event_tf3ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
           tf3.setEnabled(true);
        tf3.requestFocus();
    }//GEN-LAST:event_tf2ActionPerformed

    private void tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf4ActionPerformed
        // TODO add your handling code here:
           tf5.setEnabled(true);
        tf5.requestFocus();
    }//GEN-LAST:event_tf4ActionPerformed

    private void tf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf5ActionPerformed
        // TODO add your handling code here:
           tf6.setEnabled(true);
        tf6.requestFocus();
    }//GEN-LAST:event_tf5ActionPerformed

    private void tf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf6ActionPerformed
   tf7.setEnabled(true);
        tf7.requestFocus();
    }//GEN-LAST:event_tf6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Img;
    private javax.swing.JButton btn1;
    private javax.swing.JLabel ctr;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JPasswordField tf6;
    private javax.swing.JPasswordField tf7;
    // End of variables declaration//GEN-END:variables

}
